### PR TITLE
MassInstallAction: Install the GitHubActions workflow on this repository

### PR DESCRIPTION
**Pull request by fchorney**
This pull request sets up the GitHubActions workflow on this repository. cc: @fchorney

### CODE REVIEW

**Comment by oxinabox** [comment]
This repo doesn't actually work. It is a unfinished prototype.
But should merge this anyway

**Review by mattBrzezinski — APPROVED** [review]

**Comment by fchorney** [comment]
Hmm I am unsure why this doesn't seem to need a `DOCUMENTER_KEY`?

**Comment by mattBrzezinski** [comment]
> Hmm I am unsure why this doesn't seem to need a `DOCUMENTER_KEY`?

Probably has a GH Secret setup for it already? I don't have perms to see it.

**Comment by fchorney** [comment]
it does not, which is why im very confused

**Review by mattBrzezinski — APPROVED** [review]

**Pull request merged**
